// Defining Actions Types

export const GET_ALBUMS = "GET_ALBUMS";

const PHOTOS = {
  GET_PHOTOS: "PGET_PHOTOS",
  GET_PHOTOS_SUCCESS: "GET_PHOTOS_SUCCESS",
  GET_PHOTO_ID: "GET_PHOTO_ID",
  ADD_PHOTO: "ADD_PHOTO"
};
export { PHOTOS };
